### ISSUE TITLE
selection of points/SNPs in the locuszoom plot

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/snp_app#15]
from https://github.com/datavisyn/react-test/issues/2
sometimes selecting points (and turning them red) works, but sometimes i cannot select the point I want but another point or even multiple get selected (e.g. https://www.dropbox.com/s/euq9cspsjrhbptw/Screenshot%202016-12-06%2011.16.24.png?dl=0)

see also datavisyn/datavisyn-scatterplot#3

**Comment by sgratzl** [comment]
see also https://github.com/datavisyn/snp_app/issues/16

**Comment by sgratzl** [comment]
@andreassteffen can you update everything and try again?

**Comment by andreassteffen** [comment]
will do later. just set up new server (linux) and also got bayer docker
base container.

**Comment by andreassteffen** [comment]
i updated here on my macbook. server starts nicely, and manhattan plot works (chrome). Pressing Load Window however does not result in locuszoomplot/lineup, just nothing happens. No console output either. I will check at work setup tomorrow.

**Comment by sgratzl** [comment]
please update all repositories and the dependencies (`npm update`). Since there is no loading button anymore ;)
